node {

    withMaven(maven:'maven') {

        stage('Checkout') {
            git url: 'https://github.com/mharunor/Microservice.git', credentialsId: 'github', branch: 'master'
        }

        stage('Build') {
            mvn clean install

            def pom = readMavenPom file:'pom.xml'
            print pom.version
            env.version = pom.version
        }

        

    }

}